const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{vida: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Cronômetro: 0},
	{Projétil: 0},
	{Piscar: 0},
	{Jogadorplayer: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Teclado: 0},
	{Senóide: 0},
	{Inimigo: 0},
	{fimEsquerda: 0},
	{fimDireita: 0},
	{colisao: 0},
	{jogar: 0},
	{creditos: 0},
	{EntradaDeTexto: 0},
	{EntradaDeTexto2: 0},
	{Texto: 0},
	{Ir: 0},
	{Texto2: 0},
	{Sprite: 0},
	{DeathPit: 0},
	{Mouse: 0},
	{Toque: 0},
	{Void: 0},
	{FundoCreditos: 0},
	{Texto3: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Sprite3: 0},
	{Áudio: 0},
	{espinho: 0},
	{Sprite4: 0},
	{Voiddeath: 0},
	{Coletavel: 0},
	{Sprite5: 0},
	{Texto4: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{PontosInimigos: 0},
	{Texto5: 0},
	{PontosColetaveis: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Texto6: 0},
	{Texto7: 0},
	{Sprite10: 0},
	{Texto8: 0},
	{Texto9: 0},
	{Sprite11: 0},
	{colisao2: 0},
	{Sprite12: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Design_sem_nomeremovebgpreview: 0},
	{Sprite13: 0},
	{DesignSemNome: 0},
	{Sprite14: 0},
	{canDash: 0},
	{dashing: 0},
	{Vida: 0},
	{pontuaçãoinimigo: 0},
	{pontuaçaocoletaveis: 0}
];

self.InstanceType = {
	Jogadorplayer: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	fimEsquerda: class extends self.ISpriteInstance {},
	fimDireita: class extends self.ISpriteInstance {},
	colisao: class extends self.ISpriteInstance {},
	jogar: class extends self.ISpriteInstance {},
	creditos: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	EntradaDeTexto2: class extends self.ITextInputInstance {},
	Texto: class extends self.ITextInstance {},
	Ir: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	DeathPit: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Void: class extends self.ISpriteInstance {},
	FundoCreditos: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	espinho: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Voiddeath: class extends self.ISpriteInstance {},
	Coletavel: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	PontosInimigos: class extends self.ITextInstance {},
	Texto5: class extends self.ITextInstance {},
	PontosColetaveis: class extends self.ITextInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto8: class extends self.ITextInstance {},
	Texto9: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	colisao2: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Design_sem_nomeremovebgpreview: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	DesignSemNome: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}